@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "first commit"
echo Renaming branch to main...
git branch -M main
echo Adding remote origin...
git remote add origin https://github.com/sydrehan/Atmanirbhar-WebApp.git
echo Pushing to origin...
git push -u origin main
echo Done.
pause
